// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeachCodIT.Models;

#nullable disable

namespace TeachCodIT.Migrations
{
    [DbContext(typeof(TeachCodItContext))]
    partial class TeachCodItContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeachCodIT.Models.Achievement", b =>
                {
                    b.Property<int>("IdAchievement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Achievement");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAchievement"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Xpreward")
                        .HasColumnType("int")
                        .HasColumnName("XPReward");

                    b.HasKey("IdAchievement")
                        .HasName("PK__Achievem__BB2F175E45D233D6");

                    b.ToTable("Achievement", (string)null);
                });

            modelBuilder.Entity("TeachCodIT.Models.Course", b =>
                {
                    b.Property<int>("IdCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Course");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCourse"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("GradientColor")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdCourse")
                        .HasName("PK__Course__E2B749CDA11B0F4A");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("TeachCodIT.Models.DailyQuest", b =>
                {
                    b.Property<int>("IdQuest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Quest");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuest"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Xpreward")
                        .HasColumnType("int")
                        .HasColumnName("XPReward");

                    b.HasKey("IdQuest")
                        .HasName("PK__DailyQue__CEDD8D3A98AF8B29");

                    b.ToTable("DailyQuest", (string)null);
                });

            modelBuilder.Entity("TeachCodIT.Models.Lesson", b =>
                {
                    b.Property<int>("IdLesson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Lesson");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLesson"));

                    b.Property<string>("Content")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("Module_ID");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Xpreward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10)
                        .HasColumnName("XPReward");

                    b.HasKey("IdLesson")
                        .HasName("PK__Lesson__67381F3B754CCF23");

                    b.HasIndex("ModuleId");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("TeachCodIT.Models.LessonTask", b =>
                {
                    b.Property<int>("IdLessonTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_LessonTask");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLessonTask"));

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ExampleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int")
                        .HasColumnName("Lesson_ID");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("TaskType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Xpreward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20)
                        .HasColumnName("XPReward");

                    b.HasKey("IdLessonTask")
                        .HasName("PK__LessonTa__BDD97AA713B5EBB3");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonTask", (string)null);
                });

            modelBuilder.Entity("TeachCodIT.Models.Module", b =>
                {
                    b.Property<int>("IdModule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Module");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModule"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_ID");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdModule")
                        .HasName("PK__Module__E498BA5D5F028558");

                    b.HasIndex("CourseId");

                    b.ToTable("Module", (string)null);
                });

            modelBuilder.Entity("TeachCodIT.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Role");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRole")
                        .HasName("PK__Roles__43DCD32D3F0C80D2");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TeachCodIT.Models.StudentCourse", b =>
                {
                    b.Property<int>("IdStudentCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_StudentCourse");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudentCourse"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_ID");

                    b.Property<DateTime?>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ProgressPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("Student_ID");

                    b.HasKey("IdStudentCourse")
                        .HasName("PK__StudentC__8D37F341DF705545");

                    b.HasIndex("CourseId");

                    b.HasIndex(new[] { "StudentId", "CourseId" }, "UQ_StudentCourse")
                        .IsUnique()
                        .HasFilter("[Student_ID] IS NOT NULL AND [Course_ID] IS NOT NULL");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("TeachCodIT.Models.TaskOption", b =>
                {
                    b.Property<int>("IdOption")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Option");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOption"));

                    b.Property<bool?>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LessonTaskId")
                        .HasColumnType("int")
                        .HasColumnName("LessonTask_ID");

                    b.Property<string>("OptionText")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("IdOption")
                        .HasName("PK__TaskOpti__A8AA67B55F8BDC36");

                    b.HasIndex("LessonTaskId");

                    b.ToTable("TaskOption", (string)null);
                });

            modelBuilder.Entity("TeachCodIT.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_User");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("Role_ID");

                    b.HasKey("IdUser")
                        .HasName("PK__Users__ED4DE4424D5AFBE4");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TeachCodIT.Models.UserAchievement", b =>
                {
                    b.Property<int>("IdUserAchievement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_UserAchievement");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserAchievement"));

                    b.Property<int?>("AchievementId")
                        .HasColumnType("int")
                        .HasColumnName("Achievement_ID");

                    b.Property<DateTime?>("EarnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("IdUserAchievement")
                        .HasName("PK__UserAchi__4F1106D2A6E6C806");

                    b.HasIndex("AchievementId");

                    b.HasIndex(new[] { "UserId", "AchievementId" }, "UQ_UserAchievement")
                        .IsUnique()
                        .HasFilter("[User_ID] IS NOT NULL AND [Achievement_ID] IS NOT NULL");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("TeachCodIT.Models.UserDailyQuest", b =>
                {
                    b.Property<int>("IdUserDailyQuest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_UserDailyQuest");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserDailyQuest"));

                    b.Property<bool?>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("QuestDate")
                        .HasColumnType("date");

                    b.Property<int?>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("Quest_ID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("IdUserDailyQuest")
                        .HasName("PK__UserDail__20FCA313AF79D605");

                    b.HasIndex("QuestId");

                    b.HasIndex(new[] { "UserId", "QuestId", "QuestDate" }, "UQ_UserDailyQuest")
                        .IsUnique()
                        .HasFilter("[User_ID] IS NOT NULL AND [Quest_ID] IS NOT NULL");

                    b.ToTable("UserDailyQuests");
                });

            modelBuilder.Entity("TeachCodIT.Models.UserProfile", b =>
                {
                    b.Property<int>("IdProfile")
                        .HasColumnType("int")
                        .HasColumnName("ID_Profile");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("IdProfile")
                        .HasName("PK__UserProf__F1B3F50CFDA72C57");

                    b.HasIndex("UserId");

                    b.ToTable("UserProfile", (string)null);
                });

            modelBuilder.Entity("TeachCodIT.Models.UserProgress", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("ID_User");

                    b.Property<DateOnly?>("LastActivityDate")
                        .HasColumnType("date");

                    b.Property<int?>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("StreakDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.Property<int?>("Xp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("XP");

                    b.HasKey("IdUser")
                        .HasName("PK__UserProg__ED4DE442ADAE2B3E");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgress", (string)null);
                });

            modelBuilder.Entity("TeachCodIT.Models.UserTaskAttempt", b =>
                {
                    b.Property<int>("IdAttempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Attempt");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAttempt"));

                    b.Property<DateTime?>("AttemptDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("EarnedXp")
                        .HasColumnType("int")
                        .HasColumnName("EarnedXP");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int?>("LessonTaskId")
                        .HasColumnType("int")
                        .HasColumnName("LessonTask_ID");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("SubmittedAnswer")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("IdAttempt")
                        .HasName("PK__UserTask__701ABE91E984D707");

                    b.HasIndex("LessonTaskId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTaskAttempt", (string)null);
                });

            modelBuilder.Entity("TeachCodIT.Models.ViewModels.UserCompletedLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserCompletedLessons");
                });

            modelBuilder.Entity("TeachCodIT.Models.Course", b =>
                {
                    b.HasOne("TeachCodIT.Models.User", "CreatedByNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Course__CreatedB__571DF1D5");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("TeachCodIT.Models.Lesson", b =>
                {
                    b.HasOne("TeachCodIT.Models.Module", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Lesson__Module_I__5EBF139D");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("TeachCodIT.Models.LessonTask", b =>
                {
                    b.HasOne("TeachCodIT.Models.Lesson", "Lesson")
                        .WithMany("LessonTasks")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__LessonTas__Lesso__160F4887");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TeachCodIT.Models.Module", b =>
                {
                    b.HasOne("TeachCodIT.Models.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Module__Course_I__5BE2A6F2");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TeachCodIT.Models.StudentCourse", b =>
                {
                    b.HasOne("TeachCodIT.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__StudentCo__Cours__245D67DE");

                    b.HasOne("TeachCodIT.Models.User", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__StudentCo__Stude__236943A5");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TeachCodIT.Models.TaskOption", b =>
                {
                    b.HasOne("TeachCodIT.Models.LessonTask", "LessonTask")
                        .WithMany("TaskOptions")
                        .HasForeignKey("LessonTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__TaskOptio__Lesso__19DFD96B");

                    b.Navigation("LessonTask");
                });

            modelBuilder.Entity("TeachCodIT.Models.User", b =>
                {
                    b.HasOne("TeachCodIT.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Users__Role_ID__4BAC3F29");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TeachCodIT.Models.UserAchievement", b =>
                {
                    b.HasOne("TeachCodIT.Models.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__UserAchie__Achie__2B0A656D");

                    b.HasOne("TeachCodIT.Models.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__UserAchie__User___2A164134");

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachCodIT.Models.UserDailyQuest", b =>
                {
                    b.HasOne("TeachCodIT.Models.DailyQuest", "Quest")
                        .WithMany("UserDailyQuests")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__UserDaily__Quest__32AB8735");

                    b.HasOne("TeachCodIT.Models.User", "User")
                        .WithMany("UserDailyQuests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__UserDaily__User___31B762FC");

                    b.Navigation("Quest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachCodIT.Models.UserProfile", b =>
                {
                    b.HasOne("TeachCodIT.Models.User", "User")
                        .WithMany("UserProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__UserProfi__User___4E88ABD4");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachCodIT.Models.UserProgress", b =>
                {
                    b.HasOne("TeachCodIT.Models.User", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__UserProgr__User___5441852A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachCodIT.Models.UserTaskAttempt", b =>
                {
                    b.HasOne("TeachCodIT.Models.LessonTask", "LessonTask")
                        .WithMany("UserTaskAttempts")
                        .HasForeignKey("LessonTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__UserTaskA__Lesso__1EA48E88");

                    b.HasOne("TeachCodIT.Models.User", "User")
                        .WithMany("UserTaskAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__UserTaskA__User___1DB06A4F");

                    b.Navigation("LessonTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachCodIT.Models.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("TeachCodIT.Models.Course", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("TeachCodIT.Models.DailyQuest", b =>
                {
                    b.Navigation("UserDailyQuests");
                });

            modelBuilder.Entity("TeachCodIT.Models.Lesson", b =>
                {
                    b.Navigation("LessonTasks");
                });

            modelBuilder.Entity("TeachCodIT.Models.LessonTask", b =>
                {
                    b.Navigation("TaskOptions");

                    b.Navigation("UserTaskAttempts");
                });

            modelBuilder.Entity("TeachCodIT.Models.Module", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("TeachCodIT.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TeachCodIT.Models.User", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("StudentCourses");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserDailyQuests");

                    b.Navigation("UserProfiles");

                    b.Navigation("UserProgresses");

                    b.Navigation("UserTaskAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
